<!DOCTYPE html>
<html>
<head>
    <title>Stock Level Report</title>
    <style>
        body {
            font-family: DejaVu Sans, sans-serif;
            font-size: 12px;
            color: #000;
            margin: 20px;
        }
        h2 {
            text-align: center;
            text-transform: uppercase;
            font-size: 16px;
            margin-bottom: 5px;
        }
        p {
            margin: 2px 0;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 15px;
        }
        th, td {
            border: 1px solid #ddd;
            padding: 8px 10px;
        }
        th {
            background: #f3f3f3;
            text-align: left;
            text-transform: uppercase;
            font-size: 11px;
        }
        td {
            font-size: 12px;
        }
        .text-right {
            text-align: right;
        }
        .meta {
            margin-top: 10px;
            margin-bottom: 15px;
            font-size: 12px;
        }
        .meta strong {
            display: inline-block;
            width: 120px;
        }
        .footer {
            position: fixed;
            bottom: 20px;
            left: 0;
            right: 0;
            text-align: center;
            font-size: 10px;
            color: #666;
        }
    </style>
</head>
<body>
    <h2>Stock Level Report</h2>

    <div class="meta">
        @if(!empty($department))
            <p><strong>Department:</strong> {{ $department->name }}</p>
        @endif

        @if(request()->filled('product_name'))
            <p><strong>Product Name:</strong> {{ request('product_name') }}</p>
        @endif

        <p><strong>Generated On:</strong> {{ now()->format('Y-m-d H:i:s') }}</p>
    </div>

    <table>
        <thead>
            <tr>
                <th>Product Name</th>
                <th class="text-right">Clear Stock</th>
                <th class="text-right">Non-Clear Stock</th>
                <th class="text-right">Total Stock</th>
            </tr>
        </thead>
        <tbody>
            @forelse ($products as $product)
                <tr>
                    <td>{{ $product->name }}</td>
                    <td class="text-right">{{ $product->clear_stock_quantity }}</td>
                    <td class="text-right">{{ $product->non_clear_stock_quantity }}</td>
                    <td class="text-right" style="font-weight:bold;">{{ $product->total_stock }}</td>
                </tr>
            @empty
                <tr>
                    <td colspan="4" style="text-align:center; color:#666;">No products found for the selected filters.</td>
                </tr>
            @endforelse
        </tbody>
    </table>

    <div class="footer">
        Stock Level Report • Generated by Nsoft Admin System • {{ now()->format('Y-m-d') }}
    </div>
</body>
</html>
